### ISSUE TITLE
How to setup custom events with Typescript & React?

### ISSUE THREAD

**Issue by Eugleo** [plausible-insights/plausible#67]
Hey, sorry for (probably) stupid question, but how do I setup custom events while using Typescript? When I add the `script` tag into html, ts doesn't reflect that and throws a compilation error about `window` not having a field called `plausible`.

**Comment by ukutaht** [comment]
Hey,

I'm not very familiar with Typescript but my guess is that you need to declare the global `plausible` function so that TS can compile it. Based on a [StackOverflow thread](https://stackoverflow.com/a/12709880) I'd suggest something like:

```
declare global {
    interface Window { plausible: any; }
}
```

without knowing Typescript syntax, could also define the function signature (this is almost certainly not correct TS syntax, just to give an idea):
```
declare global {
    interface Window { plausible: function(String, Object) -> Null; }
}
```

**Comment by Eugleo** [comment]
That works, thanks! Could you add that to the docs as well, please?

**Comment by andreasvirkus** [comment]
For future reference, this would be a way to define the function signature

```
// global.d.ts
interface Window {
  plausible?: (event: string, ...args: any): void
}
```

**Comment by janosh** [comment]
@andreasvirkus I think you have some invalid syntax in there?

```ts
// global.d.ts
interface Window {
  plausible: (event: string, ...args: unknown[]) => void
}
```

**Comment by andreasvirkus** [comment]
I did, thanks!
